# Generated by Django 5.2.8 on 2025-11-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_options_order_order_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='core_client_last_na_9b60fa_idx',
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Miasto'),
        ),
        migrations.AddField(
            model_name='client',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
