# Generated by Django 5.2.8 on 2026-01-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Opłacone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Nowe'), ('in_progress', 'W trakcie'), ('done', 'Zakończone'), ('collect_payment', 'Do rozliczenia'), ('cancelled', 'Anulowane')], default='new', max_length=20),
        ),
    ]
