# Generated by Django 5.2.8 on 2026-01-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_is_paid_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Nowe'), ('in_progress', 'W trakcie'), ('done', 'Zakończone'), ('cancelled', 'Anulowane')], default='new', max_length=20),
        ),
    ]
